# Generated by Django 3.1.1 on 2020-11-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_categoria_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='image',
            new_name='imagen',
        ),
    ]
