# Generated by Django 3.1.1 on 2020-11-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201109_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='activo',
            new_name='estado',
        ),
    ]
